version: 2

jobs:
  build:
    working_directory: /src/github.com/LayerXcom/icon-score-dev
    docker:
    - image: mathetake/t-bears-docker:latest
    steps:
      - checkout
      - run: tbears test layerx
      - run: tbears test lxtSale

